backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "menu"
    label: "Menu Data"
    files:
      - file: "data/menu.json"
        label: "Menu JSON"
        format: json
        fields:
          - { label: "navMain", name: "navMain", widget: "object", required: true }
